sonar.projectKey=cookmate-frontend
sonar.projectName=CookMate Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=node_modules/**,dist/**,vite.config.ts,eslint.config.js,tailwind.config.js
sonar.language=ts
sonar.eslint.reportPaths=eslint-report.json
