package com.cookmate.main.exception;

public enum ErrorCode {
    RECIPE_NOT_FOUND,
    STEP_NOT_FOUND,
    MEAL_NOT_FOUND,
    REQUEST_VALIDATION_FAILED,
    REQUEST_BODY_INVALID,
    ARGUMENT_TYPE_MISMATCH,
    METHOD_NOT_ALLOWED,
    MEDIA_TYPE_NOT_SUPPORTED,
    EXTERNAL_SERVICE_ERROR,
    INTERNAL_SERVER_ERROR
}
